# Site settings
title: Justin's Blog
email: mojing1999@gmail.com
description: > # this means to ignore newlines until "baseurl:"
    Justin's Blog
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.justinmo.video" # the base hostname & protocol for your site
#twitter_username: jekyllrb
github_username:  mojing1999
disqus: justin

# Build settings
markdown: rdiscount


permalink: /:year/:month/:day/:title.html


